# Generated by Django 2.2 on 2019-05-16 11:36

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Выполненное задание',
                'verbose_name_plural': 'Выполненные задания',
                'db_table': 'CompletedTasks',
                'ordering': ['date', 'task__name', 'student__user__last_name'],
                'default_related_name': 'completed_tasks',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Группа')),
                ('year', models.DateField(verbose_name='Год посутпления')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'Groups',
                'ordering': ['specialty', 'name'],
                'default_related_name': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'db_table': 'Specialties',
                'default_related_name': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='students', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'Students',
                'ordering': ['user__last_name'],
                'default_related_name': 'students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'Subjects',
                'default_related_name': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'Tasks',
                'ordering': ['end_date'],
                'default_related_name': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teachers', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'Teachers',
                'default_related_name': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', app.models.DayOfTheWeekField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота')], max_length=1)),
                ('time', models.TimeField(verbose_name='Время начала пары')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Teacher')),
            ],
            options={
                'verbose_name': 'Преподаваемый предмет',
                'verbose_name_plural': 'Преподаваемые предметы',
                'db_table': 'Teacher_Subject',
                'ordering': ['subject', 'teacher', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.user_directory_path)),
                ('completed_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CompletedTask')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Task')),
            ],
            options={
                'verbose_name': 'Прикрепленный к заданию файл',
                'verbose_name_plural': 'Прикрепленные к заданиям файлы',
                'db_table': 'TaskFiles',
                'ordering': ['task'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='teacher_subjects',
            field=models.ManyToManyField(related_name='tasks', to='app.TeacherSubject'),
        ),
        migrations.CreateModel(
            name='StudentTeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Student')),
                ('teacher_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TeacherSubject')),
            ],
            options={
                'verbose_name': 'Студент преподаваемого предмета',
                'verbose_name_plural': 'Студенты преподаваемых предметов',
                'db_table': 'Student_TeacherSubject',
                'ordering': ['student__user__last_name', 'student__pk'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(verbose_name='Баллы')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата получения')),
                ('completed_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='app.CompletedTask')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'db_table': 'Marks',
                'ordering': ['date', 'completed_task__task__name', 'completed_task__student__last_name'],
                'default_related_name': 'marks',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='app.Specialty', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='app.Student'),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='app.Task'),
        ),
    ]
