# Generated by Django 2.2 on 2019-05-01 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'Groups',
                'ordering': ['specialty', 'name'],
                'default_related_name': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'db_table': 'Specialties',
                'default_related_name': 'Specialties',
            },
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'default_related_name': 'marks', 'ordering': ['date'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'default_related_name': 'students', 'ordering': ['group'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='studentteachersubject',
            options={'ordering': ['teacher_subject', 'student'], 'verbose_name': 'Студент преподаваемого предмета', 'verbose_name_plural': 'Студенты преподаваемых предметов'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'default_related_name': 'subjects', 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'default_related_name': 'tasks', 'ordering': ['taught_subject', 'start_date'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='taskfile',
            options={'ordering': ['task'], 'verbose_name': 'Прикрепленный к заданию файл', 'verbose_name_plural': 'Прикрепленные к заданиям файлы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'default_related_name': 'teachers', 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'ordering': ['subject', 'teacher', 'dayOfWeek'], 'verbose_name': 'Преподаваемый предмет', 'verbose_name_plural': 'Преподаваемые предметы'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree',
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='app.StudentTeacherSubject'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='app.Task'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='students', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentteachersubject',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Student'),
        ),
        migrations.AlterField(
            model_name='studentteachersubject',
            name='teacher_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TeacherSubject'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taught_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.TeacherSubject'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teachers', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=63, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='app.Specialty', verbose_name='Направление'),
        ),
    ]
