# Generated by Django 2.2 on 2019-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190501_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.DateField(auto_now=True, verbose_name='Год посутпления'),
        ),
    ]
