# Generated by Django 2.2 on 2019-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190517_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_meek',
            field=models.BooleanField(default=False, verbose_name='Разрешить ответы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teacher_subjects',
            field=models.ManyToManyField(related_name='tasks', related_query_name='tasks', to='app.TeacherSubject', verbose_name='Курсы'),
        ),
    ]
