# Generated by Django 2.2 on 2019-05-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_group_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'default_related_name': 'students', 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'default_related_name': 'tasks', 'ordering': ['start_date'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.RenameField(
            model_name='taskfile',
            old_name='file',
            new_name='files',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taught_subject',
        ),
        migrations.AddField(
            model_name='task',
            name='taught_subjects',
            field=models.ManyToManyField(related_name='tasks', to='app.TeacherSubject'),
        ),
        migrations.AlterField(
            model_name='group',
            name='year',
            field=models.DateField(verbose_name='Год посутпления'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Teacher'),
        ),
    ]
