# Generated by Django 2.2 on 2019-05-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190517_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'default_related_name': 'marks', 'ordering': ['date'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AddField(
            model_name='mark',
            name='completed_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', related_query_name='marks', to='app.CompletedTask'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student_teacher_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', related_query_name='marks', to='app.StudentTeacherSubject'),
        ),
    ]
