# Generated by Django 2.2 on 2019-05-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190511_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskfile',
            old_name='files',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='Дата начала'),
        ),
    ]
