# Generated by Django 2.2 on 2019-05-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190518_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='completed_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark', related_query_name='mark', to='app.CompletedTask'),
        ),
    ]
