# Generated by Django 2.2 on 2019-05-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190518_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='completed_task',
        ),
    ]
