# Generated by Django 2.2 on 2019-05-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_mark_completed_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'ordering': ['day_of_week', 'time', 'subject__name', 'teacher'], 'verbose_name': 'Преподаваемый предмет', 'verbose_name_plural': 'Преподаваемые предметы'},
        ),
    ]
