# Generated by Django 2.2 on 2019-05-22 12:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/default-avatar.png', null=True, upload_to=app.models.user_avatar_path),
        ),
    ]
