# Generated by Django 2.2 on 2019-05-22 12:25

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190522_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='settings.MEDIA_ROOT/default-avatar.png', null=True, upload_to=app.models.user_avatar_path, verbose_name='Аватар'),
        ),
    ]
