# Generated by Django 2.2 on 2019-06-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190522_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_created',
            field=models.BooleanField(default=True),
        ),
    ]
