# Generated by Django 2.2 on 2019-06-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_task_is_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_created',
        ),
    ]
