# Generated by Django 2.2 on 2019-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190602_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_created',
            field=models.BooleanField(default=True),
        ),
    ]
